### ISSUE TITLE
serve paths seem to return full element collection

### ISSUE THREAD

**Issue by erichs** [jtopjian/elements#4]
Behavior:
```
elements serve -d&
2017/03/31 03:03:58 Element path requested: system.host
```

and

```
curl localhost:8888/elements/system/host | wc -l

240
```

rather than the expected:
```
elements get -p system.host | wc -l
13
```

Seems the path selection isn't making it down into the collection that is being served as output.

**Comment by jtopjian** [comment]
Yep, confirmed. Must have been a regression in the latest refactor. Thanks!

**Comment by jtopjian** [comment]
This should be fixed now. Just pushed a new release, too. Let me know if you see any more problems :)

**Comment by erichs** [comment]
Thanks!!
